#+TITLE: Routine
#+DATE: 2023-11-12
#+SUBTITLE: On the systems great engineers keep.

I have been fortunate enough to have worked with and met a lot of
great engineers in my life, and would love to meet more. I have
written some personal logs on what I have learnt from each experience,
but this article captures a singular pick that I have noticed with
almost everyone I have met, that they all have a routine, a system.
Not a timetable, not a specifically defined set of hours where they
work in focus. But it's a system they have kept or built for
themselves over time where they have now become immune to changes in
their environment, days and other parameters. Nothing can break their
focus, their processes and their productivity.

I believe I have been able to achieve some of that myself. Here goes:

I wake up anywhere around 4 to 6 AM, that gives me a lot of control on
how I steer my day ahead. Then I work on the most primary task for the
day. But making sure that it needs to be wrapped up with a run before
8. I allow myself to be creative during these hours.

Then I return home, making myself some coffee. During this hour, I
talk to my partner due to time difference. And then I get back to plan
for the day, this is where I have set a strict time rule for 10AM to
4PM - no unnecessary social interactions or other dopamine hits unless
for work or pre-decided. This is the time that I believe allows me to
build patience and discipline. A lot of distraction due to mobile
usage, social media, videos can happen during this time if not curbed.

Usually end my day after this with some logging about the day, and
some light exercise, or yoga. I do some reading wherever I walk to,
usually to a cafe nearby. Sometimes I like to code a little more
before I sleep, but I have noticed that destroys my ability to sleep
then.

Anyway, this is my process. I could wake up a little bit later, but
that really doesn't do any harm. I get right to what I would do. Maybe
I will miss a focus session, I could pull that in later.

I don't remember where I read this "To be able to do a certain thing,
you have to be a certain person" or something along the lines.[fn:1]
But this is basically what brought me to thinking about building my
routine and sticking to it.

[fn:1] If I find out where I read it, I will add it here.
